version: '3'

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    container_name: api
    image: api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=transfer_db5
      - JWT_SECRET=secret
    depends_on:
      - db
volumes:
  pgdata: {}



